<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/archivesspace-connector.css', 'ArchivesspaceConnector'));
$this->htmlElement('body')->appendAttribute('class', 'archivesspace jobs undo browse');
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('ArchivesSpace Connector'), 1, $this->translate('Past Imports')); ?>

<?php if(empty($imports)): ?>

<?php else: ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->browse()->renderSortSelector('ac_past_imports'); ?>
</div>
<form method='POST'>
    <fieldset id='page-actions'>
        <input type='submit' value='Submit' />
    </fieldset>

    <table class="tablesaw" data-tablesaw-mode="stack" aria-label="<?php echo $this->translate('Past Imports'); ?>">
        <thead>
            <tr>
                <th scope="col"><?php echo $this->translate('Job ID'); ?></th>
                <th scope="col"><?php echo $escape($this->translate('Actions'));?></th>
                <th scope="col"><?php echo $escape($this->translate('ArchivesSpace collection'));?></th>
                <th scope="col"><?php echo $escape($this->translate('Comment'));?></th>
                <th scope="col"><?php echo $escape($this->translate('Resources'));?></th>
                <th scope="col"><?php echo $escape($this->translate('Date'));?></th>
                <th scope="col"><?php echo $escape($this->translate('Status'));?></th>
                <th scope="col"><?php echo $escape($this->translate('Owner'));?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($imports as $import): ?>
        <?php $job = $import->job(); ?>
        <?php $undoJob = $import->undoJob(); ?>
        <?php $disableOption = ($job->jobClass() == 'ArchivesspaceConnector\Job\Undo') ? 'disabled' : ''; ?>
        <?php $rerunJob = $import->rerunJob(); ?>
        <tr>
            <th scope="row"><?php echo $job->link($job->id()); ?></th>
            <td>
            <div class="archivesspace-connector-inputs" role="radiogroup" aria-label="<?php echo $this->translate('Action options'); ?>">
                <label>
                    <input type='radio' name='jobActions[<?php echo $job->id(); ?>]' value checked aria-label="<?php echo $this->translate('[No Action]'); ?>" />
                    <?php echo $this->translate('[No Action]'); ?>
                </label>
                <label>
                    <input type='radio' name='jobActions[<?php echo $job->id(); ?>]' value='undo' aria-label="<?php echo $this->translate('Undo'); ?>" <?php echo $disableOption; ?> />
                    <?php echo $this->translate('Undo'); ?>
                </label>
                <label>
                    <input type='radio' name='jobActions[<?php echo $job->id(); ?>]' value='rerun' aria-label="<?php echo $this->translate('Re-run'); ?>" <?php echo $disableOption; ?> />
                    <?php echo $this->translate('Re-run'); ?>
                </label>
            </div>
            </td>
            <td>
                <?php 
                $args = $job->args();
                $linkText = isset($args['collection_name']) ? $args['collection_name'] : $this->translate('collection link');
                if ($args['aspace_api_url'] && $args['aspace_target_path']) {
                    $apiUrl = trim($args['aspace_api_url'], '/');
                    $targetPath = trim($args['aspace_target_path'], '/');
                    $aspaceLink = $apiUrl . '/oai?verb=GetRecord&identifier=/'
                    . $targetPath . '&metadataPrefix=oai_ead';
                    echo $this->hyperlink($linkText, $aspaceLink, ['target' => '_blank']);
                }
                ?>
            </td>
            <td class="archivesspace-comment">
                <?php echo $import->comment(); ?>
            </td>
            <td class="archivesspace-resources">
                <?php
                $jobID = $job->id();
                $totalItemCount = $import->addedItems() + $import->updatedItems();
                $totalItemsetCount = $import->addedItemSets() + $import->updatedItemSets();
                // Only link to search results for Job IDs with associated items/itemSets
                $totalItemResults = $this->api()->search('items', ['archivesspace_import_id' => $jobID]);
                $totalItemsetResults = $this->api()->search('item_sets', ['archivesspace_import_id' => $jobID]);
                if ($totalItemResults->getTotalResults() > 0) {
                    echo $this->hyperlink('Total Items: ' . $totalItemResults->getTotalResults(), $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['archivesspace_import_id' => $jobID]]), ['target' => '_blank']) . '<br>';
                } else {
                    echo 'Total Items: ' . $totalItemCount . '<br>';
                }
                if ($import->addedItems() > 0) {
                    echo 'Added: ' . $import->addedItems() . '<br>';
                }
                if ($import->updatedItems() > 0) {
                    echo 'Updated: ' . $import->updatedItems() . '<br>';
                }
                if ($totalItemsetResults->getTotalResults() > 0) {
                    echo $this->hyperlink('Total Item Sets: ' . $totalItemsetResults->getTotalResults(), $this->url('admin/default', ['controller' => 'item-set', 'action' => 'browse'], ['query' => ['archivesspace_import_id' => $jobID]]), ['target' => '_blank']) . '<br>';
                } else {
                    echo 'Total Item Sets: ' . $totalItemsetCount . '<br>';
                }
                if ($import->addedItemSets() > 0) {
                    echo 'Added: ' . $import->addedItemSets() . '<br>';
                }
                if ($import->updatedItemSets() > 0) {
                    echo 'Updated: ' . $import->updatedItemSets() . '<br>';
                }
                ?>
            </td>
            <td><?php echo $escape($this->i18n()->dateFormat($job->started())); ?></td>
            
            <td>
            <?php if ($rerunJob) {
                $status = $this->translate('Reran in job ') . $rerunJob->id() . ': ' . $escape($this->i18n()->dateFormat($rerunJob->ended()));
            } else if ($undoJob) {
                $status = $this->translate('Undone in job ') . $undoJob->id() . ': ' . $escape($this->i18n()->dateFormat($undoJob->ended()));
                
            } else {
                $status = $this->translate($job->status());
            } 
            ?>
            <?php echo $status; ?>
            </td>
            <td><?php echo $this->hyperlink($job->owner()->name(), $this->url('admin/id', array('controller' => 'user', 'action' => 'show', 'id' => $job->owner()->id()))); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</form>
<?php endif; ?>
