<?php
$translate = $this->plugin('translate');
if ('sorted-desc' == $class) {
    $title = sprintf($translate('Ordered by %s descending order. Switch to ascending order'), $label);
} else {
    $title = sprintf($translate('Ordered by %s ascending order. Switch to descending order'), $label);
}
?>
<a href="<?php echo $this->escapeHtml($url); ?>"
    class="<?php echo $this->escapeHtml($class); ?>"
    aria-label="<?php echo $this->escapeHtml($title); ?>"
    title="<?php echo $this->escapeHtml($title); ?>">
    <span class="sr-only"><?php echo $this->escapeHtml($label); ?></span>
</a>